name: Trigger Gitlab Pipeline
on:
    push:
      branches:
        - main
      paths:
        - "flspp/**"
        - "tests/**"
        - "poetry.lock"
    pull_request:
      paths:
        - "flspp/**"
        - "tests/**"
        - "poetry.lock"
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build:
    name: Trigger GitLab Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Job
      uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
      with:
        host: 'gitlab.cs.uni-duesseldorf.de'
        trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
        access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        id: '3102'
        ref: 'main'
        variables: '{"PROJECT":"flspp", "GIT_HASH": "a4821bf"}'
